"""Deterministic educational corporate-credit calculation engine.

Task 1 scope: the numeric contract (``money``), the result contract (``types``), the
§2 debt and cash aggregations (``cashflow``), and the §3-§7 ratio surface (``ratios``)
of ``docs/methodology.md``.

The engine is pure. It performs no I/O, opens no network or database connection,
imports no web framework, and never uses binary floating point. Timestamps, policy
loading, and persistence belong to the layers above it and must be injected.

This package computes; it does not decide. Scorecard, capacity, stress, reverse
stress, covenant, decision, and memo modules are later tasks.
"""

from __future__ import annotations

from .cashflow import (
    adjusted_debt,
    adjusted_ebit,
    adjusted_ebitda,
    annual_debt_service,
    cfads,
    ebitda,
    ebitdar,
    eligible_cash,
    free_cash_flow,
    gross_debt,
    net_debt,
    total_debt_service,
)
from .money import (
    ENGINE_PRECISION,
    KNOWN_MINOR_UNIT_EXPONENTS,
    CurrencyMismatchError,
    Money,
    PolicyConfigurationError,
    ensure_same_currency,
    money_sum,
    normalize_reported_amount,
    scale_money,
)
from .ratios import (
    MINIMUM_VOLATILITY_PERIODS,
    adjusted_debt_to_ebitda,
    capex_to_cfo,
    capex_to_ebitda,
    cash_conversion,
    cash_plus_undrawn_revolver,
    cash_ratio,
    cashflow_volatility,
    cfads_debt_service_coverage,
    cfo_to_debt,
    current_ratio,
    debt_service_coverage,
    debt_to_capital,
    debt_to_equity,
    ebit_interest_coverage,
    ebit_margin,
    ebitda_growth,
    ebitda_margin,
    fcf_margin,
    fcf_to_cash_interest,
    fcf_to_debt,
    fixed_charge_coverage,
    gross_debt_to_ebitda,
    interest_coverage,
    invested_capital,
    liabilities_to_assets,
    liquidity_runway_months,
    margin_volatility,
    net_debt_to_ebitda,
    positive_fcf_years,
    quick_ratio,
    return_on_assets,
    return_on_invested_capital,
    revenue_growth,
    revenue_volatility,
    safe_ratio,
    secured_debt_to_total,
    short_term_debt_coverage,
    sources_uses_surplus,
    working_capital,
)
from .types import (
    ADVERSE_NM_REASONS,
    FAVORABLE_NM_REASONS,
    RATIO_QUANTUM,
    ConfidenceLevel,
    MetricComponent,
    MoneyMetricResult,
    RatioReason,
    RatioResult,
    RatioStatus,
)

__version__ = "0.1.0"

__all__ = [
    "ADVERSE_NM_REASONS",
    "ENGINE_PRECISION",
    "FAVORABLE_NM_REASONS",
    "KNOWN_MINOR_UNIT_EXPONENTS",
    "MINIMUM_VOLATILITY_PERIODS",
    "RATIO_QUANTUM",
    "ConfidenceLevel",
    "CurrencyMismatchError",
    "MetricComponent",
    "Money",
    "MoneyMetricResult",
    "PolicyConfigurationError",
    "RatioReason",
    "RatioResult",
    "RatioStatus",
    "__version__",
    "adjusted_debt",
    "adjusted_debt_to_ebitda",
    "adjusted_ebit",
    "adjusted_ebitda",
    "annual_debt_service",
    "capex_to_cfo",
    "capex_to_ebitda",
    "cash_conversion",
    "cash_plus_undrawn_revolver",
    "cash_ratio",
    "cashflow_volatility",
    "cfads",
    "cfads_debt_service_coverage",
    "cfo_to_debt",
    "current_ratio",
    "debt_service_coverage",
    "debt_to_capital",
    "debt_to_equity",
    "ebit_interest_coverage",
    "ebit_margin",
    "ebitda",
    "ebitda_growth",
    "ebitda_margin",
    "ebitdar",
    "eligible_cash",
    "ensure_same_currency",
    "fcf_margin",
    "fcf_to_cash_interest",
    "fcf_to_debt",
    "fixed_charge_coverage",
    "free_cash_flow",
    "gross_debt",
    "gross_debt_to_ebitda",
    "interest_coverage",
    "invested_capital",
    "liabilities_to_assets",
    "liquidity_runway_months",
    "margin_volatility",
    "money_sum",
    "net_debt",
    "net_debt_to_ebitda",
    "normalize_reported_amount",
    "positive_fcf_years",
    "quick_ratio",
    "return_on_assets",
    "return_on_invested_capital",
    "revenue_growth",
    "revenue_volatility",
    "safe_ratio",
    "scale_money",
    "secured_debt_to_total",
    "short_term_debt_coverage",
    "sources_uses_surplus",
    "total_debt_service",
    "working_capital",
]
